language: node_js

node_js:
- lts/*

install:
- npm install

cache:
  directories:
  - "node_modules"

addons:
  firefox: latest

services:
- xvfb

script:
- npm run build
- npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist-app
  on:
    branch: master
